### ISSUE TITLE
Port changes from D7 version 7.x-3.2

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/weight#7]
Weight version 7.x-3.2 was released in Feb 2023. This is the list of commits:

https://git.drupalcode.org/project/weight/-/compare/7.x-3.1...7.x-3.2

Those should be ported to Backdrop and a new release will be needed. Additionally, the new release needs to change the major version number to match "3" in D7.
- [X] N/A (already in Backdrop) | [e7051c1](https://git.drupalcode.org/project/weight/-/commit/e7051c1f8c108006a8c2294d5a990ddefb3b321e) | [Issue #2674418 by andrew.chappell: No assign node weight permission](https://www.drupal.org/i/2674418)
- [X] N/A (already in Backdrop) | [35ba015](https://git.drupalcode.org/project/weight/-/commit/35ba015bbad0b0dc1e20c919a7ec2f6210cddbb9) | [Issue #2632640 by koykov, StryKaizer: Tabledrag doesn't work for non-admin users](https://www.drupal.org/project/weight/issues/2632640)
- [X] N/A (already in Backdrop) | [3d030ac](https://git.drupalcode.org/project/weight/-/commit/3d030ac66083f5af83fc82a5716a8482a0820b86) | [Issue #1233530 by kevinquillen: Weights for 'user' entity](https://www.drupal.org/project/weight/issues/1233530)
- [X] N/A (already in Backdrop) | [6a4e159](https://git.drupalcode.org/project/weight/-/commit/6a4e15971a7b3fd7453901a7be7ee07710c75b01) | [Issue #2728581 by kevinquillen: Accessibility: add a title for weight selector](https://www.drupal.org/project/weight/issues/2728581)
- [X] [Will not fix](https://github.com/backdrop-contrib/weight/issues/8) | [8cad555](https://git.drupalcode.org/project/weight/-/commit/8cad555fe251f293b7373f46b5ccc72a8fe8a367) | [Issue #2764913 by ozin: Tabledrag initialized even when no result and "Save" is displayed as well](https://www.drupal.org/project/weight/issues/2764913)
- [X] https://github.com/backdrop-contrib/weight/issues/10  | [fd51a10](https://git.drupalcode.org/project/weight/-/commit/fd51a101d57f7a6b0c89b3b32c39c44c86230c0a) | [Issue #3280618 by piotrsmykaj: Trying to access array offset on value of type null w FieldInfo->prepareInstanceDisplay()](https://www.drupal.org/project/weight/issues/3280618)
- [X] https://github.com/backdrop-contrib/weight/issues/12 | [facb754](https://git.drupalcode.org/project/weight/-/commit/facb754032f36b630f1c053f97f0ec772611fdaf) | [Issue #2826586 by seanB, VladimirAus: Weight default value is an array, error when saving](https://www.drupal.org/project/weight/issues/2826586)
- [X] Can't reproduce | [7ae3bac](https://git.drupalcode.org/project/weight/-/commit/7ae3bacb502f752bb3d07941432971b014a1a0ab) | [Issue #2096231 by Ludo.R, williamhicks, VladimirAus: Unable to create draggable view with relationship](https://www.drupal.org/project/weight/issues/2096231)
- [X] #16  | [53ca1d6](https://git.drupalcode.org/project/weight/-/commit/53ca1d617f2b6778a81ca4de5a8609562f43a1de) | [Issue #2844849 by maurizio.ganovelli, y_h, Sohal Khatwani, VladimirAus: Does this module work with Feeds?](https://www.drupal.org/project/weight/issues/2844849)
- [X] N/A (this was relevant for D7 upgrades from 7.2 to 7.3) | [4bcdf30](https://git.drupalcode.org/project/weight/-/commit/4bcdf30378b4a01f7691868cc0943b72b428d205) | [Issue #3214098 by Mile23, VladimirAus: Speed improvement for weight_update_7301()](https://www.drupal.org/project/weight/issues/3214098)

Generated with `git log  7.x-3.1..7.x-3.2 --reverse --no-merges --pretty=format:"- [ ] #xx | [%h](https://git.drupalcode.org/project/weight/-/commit/%H) | [%s](https://www.drupal.org/project/weight/issues/)"`

**Comment by argiepiano** [comment]
Completed.
